name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Backend image
      run: docker build backend/ --file Dockerfile --tag ece461-web-backend:$(date +%s)
      
    - uses: actions/checkout@v3
    - name: Build the Frontend image
      run: docker build frontend/ --file Dockerfile --tag ece461-web-frontend:$(date +%s)
